export default {
    loggedIn: false,
    userName: '',
    allPlantsByType: [],
    userPlantList: [],
    lastTab: 0,
    userInfo: {},
    userGardens: [],
    userAllGardenPlants: [],
    gardenId: 1,
    selectedIndexNum: 0,
    createGarden: {
        garden_id: 0,
        width: 0,
        length: 0,
        zipcode: 0,
        beds: [],
        currentItem: {},
        layout: [],
    },
    allGardenBeds: [],
    gridLayout: [],
    gardenPlantArray: {},
}